### ISSUE TITLE
Configure Request ?

### ISSUE THREAD

**Issue by mhabsaoui** [OpenTriply/YASGUI#113]
Hi,

Just wondering what exactly is the the "configure request pane" for : only configuring (e.g. POST a new RDF file to a triple-store endpoint...) the SPARQL request that is written in the editor, or is it more than that ? 

What's the role of this feature (as not well documented in docs it seems) ?

![image](https://user-images.githubusercontent.com/18755135/31072279-9075557a-a767-11e7-9bff-ab652d666597.png)

Thanks.

**Comment by LaurensRietveld** [comment]
It doesn't support posting a new RDF file to the endpoint (that is not part of the SPARQL spec). It simply allows you to modify the request sent to the endpoint. Useful when you e.g. have authentication (then you can add an http header), when you'd like a different response format (e.g. csv instead of json), or when you'd like to query a particular set of graphs

**Comment by mhabsaoui** [comment]
Thanks for your info :+1:
