### ISSUE TITLE
Feature request - support terp syntax

### ISSUE THREAD

**Issue by alanruttenberg** [OpenTriply/YASGUI#66]
http://ceur-ws.org/Vol-614/owled2010_submission_14.pdf
Github source (java) at https://goo.gl/hi1JI1
Presentation: http://www.slideshare.net/candp/owled-2010-terp

I believe this is just some syntactic sugar on top of SPARQL. It's very helpful for people who have to write OWL queries.

**Comment by LaurensRietveld** [comment]
I assume you'd be interested in not only terp syntax highlighting and validation, but also a transformation to native SPARQL right? (in the background)

**Comment by alanruttenberg** [comment]
Yes

**Comment by LaurensRietveld** [comment]
From a first glance, going beyond syntax highlighting and validation would require a proper parser in YASQE. Something to both dissect the query with terp syntax, as well as generate a new native SPARQL one. 
SPARQL.js (https://github.com/RubenVerborgh/SPARQL.js) would be a nice fit for something like this.

Last I heard was that our friends from Gent wanted to integrate sparql.js into YASQE. I prefer to wait for that, as it would result in a cleaner implementation than the current YASQE library allows for.

**Comment by wouterbeek** [comment]
There is already an issue for this in the YASR repository (which is where TERP support would have to be located): https://github.com/OpenTriply/YASGUI.YASQE/issues/85  That issue has been closed though, because there should first be (1) a formal syntax for TERP that allows efficient parsing, (2) a transformation from TERP AST to SPARQL AST.

(IMO it's best if people who develop TERP, or take an interest in using it, integrate (1) and (2) into a fork of YASQE themselves.  Although a very interesting syntactic improvement, it is unlikely that [Triply](https://triply.cc) programmers will have time to implement TERP in the foreseeable future themselves.)
