### ISSUE TITLE
Show construct SPARQL results

### ISSUE THREAD

**Issue by jmvanel** [OpenTriply/YASGUI#90]
Apparently today only SELECT SPARQL results are displayed in UI,
although the CONSTRUCT SPARQL query is sent to server.

It would probably be easy to display the resulting triples in a 3 columns table.

**Comment by LaurensRietveld** [comment]
This is supported when you request the response as CSV or json (see e.g. http://yasgui.org/short/B1Hvw0eLe). For the other formats to work, I'd need to include a few parsers. I'm inclined not to do that though: the gain is little, where the JS lib size will only increase because of the added dependencies

**Comment by jmvanel** [comment]
Yes , indeed it's fine, it's just that the menu under "Graph" is misleading;
it shows Turtle, etc : things that do not really work (although the query is indeed sent ) .

**Comment by LaurensRietveld** [comment]
hmm, not sure what you mean. Why doesn't really work? Do you get back an error from the endpoint, or a different representation as the one you were expecting?

**Comment by LaurensRietveld** [comment]
if there are remaining issues, let me know. closing for now
